[project]
name = "biobert-to-onnx"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "onnxruntime-tools>=1.7.0",
    "optimum[onnxruntime]>=1.24.0",
    "transformers>=4.48.3",
]
